### ISSUE TITLE
Thank you so much 

### ISSUE THREAD

**Issue by HiddenPirates** [pjgowtham/android_device_oplus_RMX3360#1]
Thank you very very much for creating this. I was waiting for this. ♥️♥️
Now waiting for vendor tree and kernel tree of this device RMX3360.
But why you give **oplus** brand name instead of **Realme**

**Comment by pjgowtham** [comment]
./extract-files.sh complicates things if i name the common tree oplus and device tree as realme. So its named as oplus.
