### ISSUE TITLE
No OTG?

### ISSUE THREAD

**Issue by aprilmay** [pjgowtham/android_device_oplus_RMX3360#12]
My device does not seem to recognise any USB device, eg. USB-C pen drive.

I have checked that:
- USB works well (adb)
- the USB drives (Sandisk) work without issue on another phone, a Redmi K20 also running LineageOS.

I cannot find any trace of OTG setting, nor the file as in https://android.stackexchange.com/questions/139240/can-i-use-the-adb-shell-to-know-that-the-phone-support-otg-or-not , or nothing related to OTG that i found during a quick search on the web.

Am i missing something? Thanks!

**Comment by pjgowtham** [comment]
The latest build hopefully fixes that for you

[lineage-20.0-20231018-UNOFFICIAL-lunaa](https://github.com/pjgowtham/android_device_realme_lunaa/releases/tag/lineage-20.0-20231018-UNOFFICIAL-lunaa)

**Comment by aprilmay** [comment]
@pjgowtham Yes! You're amazing, thanks a ton
