### ISSUE TITLE
Trebuchet issue 

### ISSUE THREAD

**Issue by enonawcg** [pjgowtham/android_device_oplus_RMX3360#4]
Hi,
With last version 20, Trebuchet crashes immediately. I've reinstalled many times (with data wipe) but the problem persists. I had to install Nova launcher to be able to use the smartphone. And there is not gesture navigation mode, only 3-buttons.
Best regards

**Comment by pjgowtham** [comment]
No issues with trebuchet here and for others. You might be using android-12.1 gapps on android-13.0 which might cause this issue.
I've personally tested the omni package from here on lineage-20.0 and it works fine.

https://sourceforge.net/projects/nikgapps/files/Releases/NikGapps-T/08-Sep-2022/

There is no mindthegapps available right now for T

**Comment by enonaw** [comment]
Good evening, I'm sorry, I tried the update last night when I got home from the office, I was tired and didn't do everything by the book. I did it again tonight and everything is perfect ! Thanks a lot for your work and your contribution to a free world ;-)
