### ISSUE TITLE
Cannot update to lineage-20.0-20230328-UNOFFICIAL-lunaa

### ISSUE THREAD

**Issue by aprilmay** [pjgowtham/android_device_oplus_RMX3360#7]
Flashing with `adb sideload` gives this error: 
`Error: recovery: Package is for product RE54ABL1 but expected RMX3360`
Note that i tried upgrading from `lineage-20.0-20230206-UNOFFICIAL-RMX3360`.

Thanks again for the hard work!

**Comment by pjgowtham** [comment]
You can flash the recovery from here to install newer builds

https://github.com/pjgowtham/android_device_realme_lunaa/releases/download/lineage-20.0-20230220-UNOFFICIAL-lunaa/lineage-20.0-20230220-UNOFFICIAL-recovery-lunaa.zip
