### ISSUE TITLE
Signature Spoofing on  lineage-20.0-20230206-UNOFFICIAL-RMX3360

### ISSUE THREAD

**Issue by maikuITA** [pjgowtham/android_device_oplus_RMX3360#8]
I flashed the ROM to my RMX3363 but i can't enable signature spoofing from Microg Core.

**Comment by 1alessandro1** [comment]
Hi @pjgowtham, I have the same phone and the same issue occurs, when will this ROM recieve signature spoofing support?

**Comment by pjgowtham** [comment]
Could you try it on the latest release

https://github.com/pjgowtham/android_device_realme_lunaa/releases/download/lineage-20.0-20230404-UNOFFICIAL-lunaa/lineage-20.0-20230404-UNOFFICIAL-lunaa.zip

**Comment by 1alessandro1** [comment]
@pjgowtham what custom recovery do we have to use to flash this update?
