### ISSUE TITLE
Documentation file?

### ISSUE THREAD

**Issue by maikuITA** [pjgowtham/android_device_oplus_RMX3360#9]
You should add a readme/guide file to your builds, otherwise people (like me) have to waste hours on hours on figuring out how to do everything correctly.
I posted a [How-To guide](https://forum.xda-developers.com/t/simplified-guide-on-how-to-unlock-rmx336x-bootloader-flash-lineageos-and-get-root-privileges.4571203/#post-88359849) if anyone wants.

**Comment by pjgowtham** [comment]
https://lineage.youd.dev/350016/5/devices/lunaa/
